[settings]
experimental = true
minimum_release_age = "1d"
npm.package_manager = "bun"
pipx.uvx = true

[tools]
"pipx:yt-dlp" = "latest"

bun = "1"
ffmpeg = "8"
gh = "2"
hk = "1.51.0"
node = "24"
pkl = "0.32"
usage = "latest"
uv = "0.11"

[env]
PROJECT_ROOT = "{{config_root}}"

[hooks]
enter = ["hk install --mise"]
